'use client';
import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowUpRight, Save, ImagePlus } from 'lucide-react';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog';
import { FACEBOOK, type SchoolContent, type NewsPost } from '@/lib/content';
const emptyPost=():NewsPost=>({id:crypto.randomUUID(),title:'',category:'Announcement',date:new Date().toLocaleDateString('en-CA'),body:'',image:'',source:''});
export default function ContentEditor({initialContent,initialRevision,available,name,signOutHref}:{initialContent:SchoolContent;initialRevision:number;available:boolean;name:string;signOutHref:string}){
  const [content,setContent]=useState(initialContent),[revision,setRevision]=useState(initialRevision),[post,setPost]=useState<NewsPost|null>(null);
  const [busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[dirty,setDirty]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(false);
  const [galleryDraft,setGalleryDraft]=useState({url:'',caption:'',source:''});
  const [remove,setRemove]=useState<{type:'posts'|'gallery';id:string}|null>(null);
  function update<K extends keyof SchoolContent>(key:K,value:SchoolContent[K]){setContent(c=>({...c,[key]:value}));setDirty(true);setMessage('');}
  function report(text:string,isError=false){setMessage(text);setError(isError);}
  useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
  useEffect(()=>{
    const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,opts:unknown)=>Promise<void>}}).modelContext;
    if(!context?.registerTool)return; const lifecycle=new AbortController();
    Promise.resolve(context.registerTool({name:'stage_school_notice',title:'Edit school notice',description:'Stage a notice in the visible editor. Does not save or publish. The user must review and click Save website changes.',inputSchema:{type:'object',properties:{notice:{type:'string',minLength:1,maxLength:400}},required:['notice'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const v=input as {notice?:unknown};if(typeof v.notice!=='string'||!v.notice.trim()||v.notice.length>400)throw new Error('Provide a notice between 1 and 400 characters.');update('notice',v.notice.trim());return {status:'staged',saved:false};}},{signal:lifecycle.signal})).catch(console.error);return()=>lifecycle.abort();
  },[]);
  async function upload(file:File|undefined,onDone:(url:string)=>void){if(!file)return;setUploading(true);try{const form=new FormData();form.set('file',file);const r=await fetch('/api/upload',{method:'POST',body:form});const data=await r.json() as {error?:string;url?:string};if(!r.ok||!data.url)throw new Error(data.error||'Upload failed.');onDone(data.url);report('Photo uploaded. Save your website changes to make it visible.');}catch(e){report(e instanceof Error?e.message:'Upload failed.',true);}finally{setUploading(false);}}
  async function save(){setBusy(true);report('');try{const r=await fetch('/api/content',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:content,revision})});const d=await r.json() as {error?:string;revision?:number};if(!r.ok||typeof d.revision!=='number')throw new Error(d.error||'Could not save.');setRevision(d.revision);setDirty(false);report('Your website changes are saved.');}catch(e){report(e instanceof Error?e.message:'Could not save. Please try again.',true);}finally{setBusy(false);}}
  const validFacebook=(url:string)=>/^https:\/\/(www\.)?facebook\.com\/(pupotsanNHS(?:\/|\?|$)|photo\/?\?)/i.test(url);
  function addPost(){if(!post?.title.trim()||!post.body.trim()||!post.date){report('Add a title, date, and announcement text.',true);return;}if(post.source&&!validFacebook(post.source)){report('Use a post link from the school Facebook page.',true);return;}update('posts',[post,...content.posts.filter(p=>p.id!==post.id)].sort((a,b)=>b.date.localeCompare(a.date)));setPost(null);report('Announcement added to your changes. Save when ready.');}
  return <main className="admin-page"><div className="container"><a href="/" className="text-link"><ArrowLeft size={16}/> Back to school website</a><div className="admin-top"><div><p className="eyebrow" style={{marginTop:30}}>PUPOTSAN NATIONAL HIGH SCHOOL</p><h1>Manage your website</h1><p>Welcome, {name}. Update school information and announcements.</p></div><div style={{display:'flex',gap:10,alignItems:'center'}}><a href="/" target="_blank" rel="noreferrer" className="button button-outline">View website <ArrowUpRight size={17}/></a><a href={signOutHref} className="text-link">Sign out</a></div></div>
    {!available&&<p className="status-message error">Content could not be loaded. Reload this page before editing.</p>}
    <div className="admin-grid"><div><section className="editor-panel"><h2>School information</h2><label htmlFor="notice">Homepage notice</label><textarea id="notice" maxLength={400} value={content.notice} onChange={e=>update('notice',e.target.value)}/><label htmlFor="enrollment">Enrollment schedule & instructions</label><textarea id="enrollment" maxLength={3000} value={content.enrollment} onChange={e=>update('enrollment',e.target.value)}/><label htmlFor="requirements">Document requirements</label><textarea id="requirements" maxLength={3000} value={content.requirements} onChange={e=>update('requirements',e.target.value)}/></section>
    <section className="editor-panel"><h2>Homepage photo</h2><p>Use a campus photo from the school’s Facebook page. Add its original post link for attribution.</p>{content.heroImage&&<img src={content.heroImage} alt="Current homepage photo" className="editor-image"/>}<label htmlFor="hero-upload">Upload campus photo (JPG, PNG, WebP · up to 5 MB)</label><input id="hero-upload" type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading} onChange={e=>upload(e.target.files?.[0],url=>update('heroImage',url))}/><label htmlFor="hero-source">Original Facebook photo link</label><input type="url" id="hero-source" value={content.heroSource} onChange={e=>update('heroSource',e.target.value)} placeholder={FACEBOOK}/></section>
    <section className="editor-panel"><h2>Campus gallery</h2><p>Add photos from the school’s Facebook page.</p>{content.gallery.map(p=><div className="editor-list-item" key={p.id}><strong>{p.caption}</strong><button className="text-link" onClick={()=>setRemove({type:'gallery',id:p.id})}>Remove</button></div>)}<label htmlFor="gallery-upload">School photo</label><input type="file" id="gallery-upload" accept="image/jpeg,image/png,image/webp" disabled={uploading} onChange={e=>upload(e.target.files?.[0],url=>setGalleryDraft(g=>({...g,url})))}/>{galleryDraft.url&&<img className="editor-image" src={galleryDraft.url} alt="New gallery photo"/>}<label htmlFor="caption">Photo caption</label><input id="caption" value={galleryDraft.caption} maxLength={200} onChange={e=>setGalleryDraft(g=>({...g,caption:e.target.value}))}/><label htmlFor="gallery-source">Original Facebook photo link</label><input id="gallery-source" type="url" value={galleryDraft.source} onChange={e=>setGalleryDraft(g=>({...g,source:e.target.value}))}/><button className="button button-outline" disabled={uploading} onClick={()=>{if(!galleryDraft.url||!galleryDraft.caption.trim()||!validFacebook(galleryDraft.source)){report('Add a photo, caption, and original school Facebook link.',true);return;}update('gallery',[...content.gallery,{...galleryDraft,id:crypto.randomUUID()}]);setGalleryDraft({url:'',caption:'',source:''});report('Gallery photo added. Save when ready.');}}><ImagePlus size={17}/> Add gallery photo</button></section></div>
    <div><section className="editor-panel"><h2>Announcements</h2><p>Create school updates with confirmed details and dates.</p>{!content.posts.length&&<p style={{marginTop:15}}>No website announcements yet.</p>}{content.posts.map(p=><div key={p.id} className="editor-list-item"><div><strong>{p.title}</strong><p>{p.date} · {p.category}</p></div><div className="editor-actions"><button className="text-link" onClick={()=>setPost({...p})}>Edit</button><button className="text-link" onClick={()=>setRemove({type:'posts',id:p.id})}>Remove</button></div></div>)}<button className="button button-green" onClick={()=>setPost(emptyPost())}>New announcement</button></section>
    {post&&<section className="editor-panel"><h2>{content.posts.some(p=>p.id===post.id)?'Edit announcement':'New announcement'}</h2><label htmlFor="post-title">Title</label><input id="post-title" maxLength={160} value={post.title} onChange={e=>setPost({...post,title:e.target.value})}/><label htmlFor="category">Category</label><Select value={post.category} onValueChange={category=>setPost({...post,category})}><SelectTrigger id="category" className="w-full"><SelectValue/></SelectTrigger><SelectContent>{['Announcement','Enrollment','Campus life','Achievement'].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select><label htmlFor="post-date">Date</label><input id="post-date" type="date" value={post.date} onChange={e=>setPost({...post,date:e.target.value})}/><label htmlFor="post-body">Announcement</label><textarea id="post-body" maxLength={6000} rows={8} value={post.body} onChange={e=>setPost({...post,body:e.target.value})}/><label htmlFor="post-photo">Optional photo from the school Facebook page</label><input id="post-photo" type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading} onChange={e=>upload(e.target.files?.[0],image=>setPost(p=>p?{...p,image}:p))}/>{post.image&&<img src={post.image} alt="Announcement photo" className="editor-image"/>}<label htmlFor="post-source">Original Facebook post link</label><input id="post-source" type="url" value={post.source} onChange={e=>setPost({...post,source:e.target.value})}/><div className="editor-actions"><button className="button button-green" onClick={addPost} disabled={uploading}>Apply announcement</button><button className="button button-outline" onClick={()=>setPost(null)}>Cancel</button></div></section>}
    <section className="editor-panel"><h2>Before you save</h2><p>Confirm enrollment dates, requirements, and announcement details with the school. Photos should come from the Pupotsan National High School Facebook page.</p><p style={{marginTop:15}}>Only people with the admin password can reach this page.</p></section></div></div>
    {message&&<p role={error?'alert':'status'} className={'status-message '+(error?'error':'')}>{message}</p>}
    <div className="admin-save"><p>{uploading?'Uploading photo…':dirty?'You have unsaved changes.':'All changes saved.'}</p><button className="button button-green" disabled={busy||uploading||!available||!dirty} onClick={save}><Save size={16}/>{busy?'Saving…':'Save website changes'}</button></div>
    <AlertDialog open={!!remove} onOpenChange={v=>!v&&setRemove(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Remove this {remove?.type==='posts'?'announcement':'photo'}?</AlertDialogTitle><AlertDialogDescription>It will be removed from the website after you save your changes.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep it</AlertDialogCancel><AlertDialogAction onClick={()=>{if(remove?.type==='posts')update('posts',content.posts.filter(p=>p.id!==remove.id));if(remove?.type==='gallery')update('gallery',content.gallery.filter(p=>p.id!==remove.id));setRemove(null);}}>Remove</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div></main>;
}
