'use client';
import { useState } from 'react';
import { ArrowUpRight, ArrowRight, BookOpen, GraduationCap, MapPin, Megaphone, Menu, X, CalendarDays, ExternalLink } from 'lucide-react';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { FACEBOOK, type SchoolContent, type NewsPost } from '@/lib/content';
const nav = [['About','about'],['Academics','academics'],['Announcements','announcements'],['Campus life','campus-life']];
export default function SchoolWebsite({initialContent,storageAvailable}:{initialContent:SchoolContent;storageAvailable:boolean}) {
  const [menu,setMenu] = useState(false);
  const [article,setArticle] = useState<NewsPost|null>(null);
  const [photo,setPhoto] = useState<SchoolContent['gallery'][number]|null>(null);
  const c=initialContent;
  return <>
    <a href="#main" className="skip-link">Skip to content</a>
    <div className="utility"><div className="container utility-inner"><span>Taod-oy, Magallanes, Agusan del Norte</span><a href={FACEBOOK} target="_blank" rel="noreferrer">Connect with us on Facebook <ArrowUpRight size={14}/></a></div></div>
    <header className="site-header"><div className="container header-inner">
      <a href="#" className="brand" aria-label="Pupotsan National High School home"><img src="/school-logo.png" alt="Pupotsan National High School seal" width="58" height="58"/><span>PUPOTSAN<span>NATIONAL HIGH SCHOOL</span></span></a>
      <nav className="desktop-nav" aria-label="Main navigation">{nav.map(([label,id])=><a key={id} href={'#'+id}>{label}</a>)}</nav>
      <a className="button button-green header-cta" href="#enrollment">Enrollment guide <ArrowUpRight size={16}/></a>
      <button className="menu-button" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button>
    </div>{menu&&<nav className="mobile-nav" aria-label="Mobile navigation">{[...nav,['Enrollment guide','enrollment'],['Contact','contact']].map(([label,id])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{label}<ArrowUpRight size={16}/></a>)}</nav>}</header>
    <main id="main">
      <section className="hero"><div className="container hero-grid">
        <div className="hero-copy"><p className="eyebrow"><span className="eyebrow-line"/>WELCOME TO PUPOTSAN</p><h1>A place to learn.<br/>A community<br/>to <em>grow with.</em></h1><p className="hero-description">Welcome to Pupotsan National High School. Your next chapter starts here, in the heart of Taod-oy, Magallanes.</p><div className="hero-actions"><a className="button button-green" href="#enrollment">Explore enrollment <ArrowUpRight size={18}/></a><a className="text-link" href="#about">Get to know our school <ArrowRight size={17}/></a></div><div className="hero-footnote"><BookOpen size={18}/><span>Junior High School <span className="divider-dot">·</span> Senior High School</span></div></div>
        <div className={'hero-visual '+(c.heroImage?'with-photo':'with-seal')}>
          {c.heroImage?<img className="hero-photo" src={c.heroImage} alt="Campus life at Pupotsan National High School" fetchPriority="high"/>:<div className="seal-panel"><span className="seal-panel-top">PUPOTSAN NATIONAL HIGH SCHOOL</span><img className="hero-seal" src="/school-logo.png" alt="School seal with a book, torch and greenery"/><span className="seal-panel-bottom">MAGALLANES DISTRICT</span></div>}
          <div className="hero-caption"><span>OUR SCHOOL. OUR COMMUNITY.</span><p>Rooted in Magallanes.<br/>Looking toward the future.</p>{c.heroSource&&<a href={c.heroSource} target="_blank" rel="noreferrer" aria-label="View original photo on Facebook"><ArrowUpRight size={20}/></a>}</div>
        </div>
      </div></section>
      <div className="notice"><div className="container notice-inner"><div className="notice-label"><Megaphone size={18}/><strong>SCHOOL NOTICE</strong></div><p>{c.notice}</p><a href={FACEBOOK} target="_blank" rel="noreferrer">View updates <ArrowRight size={16}/></a></div></div>
      <div className="container quick-links"><a href="#enrollment"><span className="quick-icon"><GraduationCap/></span><span><strong>Enrollment information</strong><small>Start your next school chapter</small></span><ArrowUpRight/></a><a href="#announcements"><span className="quick-icon"><CalendarDays/></span><span><strong>School announcements</strong><small>Stay connected and informed</small></span><ArrowUpRight/></a><a href="#contact"><span className="quick-icon"><MapPin/></span><span><strong>Visit & contact us</strong><small>Find your way to our school</small></span><ArrowUpRight/></a></div>
      <section className="section about-section container" id="about"><div className="about-heading"><p className="eyebrow">GET TO KNOW US</p><h2>Learning together.<br/><em>Growing together.</em></h2></div><div className="about-copy"><p className="lead">A school at the heart of its community.</p><p>Pupotsan National High School is located in Taod-oy, Magallanes, Agusan del Norte. This is a place for students, families, and teachers to connect around learning.</p><p>Explore Junior and Senior High School information, keep up with school activities, and find the guidance you need for your next step.</p><a className="text-link" href={FACEBOOK} target="_blank" rel="noreferrer">Meet our community on Facebook <ArrowUpRight size={17}/></a></div></section>
      <section className="academics-section section" id="academics"><div className="container"><div className="section-heading"><div><p className="eyebrow">LEARN. EXPLORE. MOVE FORWARD.</p><h2>Your learning journey</h2></div><p>Find your next step at<br/>Pupotsan National High School.</p></div><div className="academic-grid"><article className="academic-card"><span className="academic-number">01 / JUNIOR HIGH</span><BookOpen className="academic-icon"/><div><h3>Build your foundation.</h3><p>Find information for incoming, returning, and transfer Junior High School learners.</p><a href="#enrollment" className="text-link">Junior High enrollment <ArrowUpRight size={18}/></a></div><span className="grade-label">GRADES 7–10</span></article><article className="academic-card senior"><span className="academic-number">02 / SENIOR HIGH</span><GraduationCap className="academic-icon"/><div><h3>Take your next step.</h3><p>Senior High learners can enroll in the strand currently listed below.</p><div className="strand-highlight"><span>AVAILABLE STRAND</span>{c.seniorHighStrands.map(strand=><strong key={strand}>{strand}</strong>)}</div><div className="program-notes"><span>{c.seniorHighCertification}</span>{c.acceptsAls&&<span>ALS learners welcome</span>}</div><a href="#enrollment" className="text-link">Senior High enrollment <ArrowUpRight size={18}/></a></div><span className="grade-label">GRADES 11–12</span></article></div></div></section>
      <section className="section container" id="announcements"><div className="section-heading"><div><p className="eyebrow">THE SCHOOL BULLETIN</p><h2>News & announcements</h2></div><a className="text-link" href={FACEBOOK} target="_blank" rel="noreferrer">All updates on Facebook <ArrowUpRight size={18}/></a></div>{!storageAvailable&&<p className="subtle-note">Website updates are temporarily unavailable. Please check the school’s Facebook page for the latest news.</p>}<div className="news-grid">{c.posts.length?c.posts.map(post=><article className="news-card" key={post.id}>{post.image&&<img src={post.image} alt={post.title} loading="lazy"/>}<div className="news-card-body"><div className="news-meta"><span>{post.category}</span><time dateTime={post.date}>{new Date(post.date+'T12:00:00').toLocaleDateString('en-PH',{month:'short',day:'numeric',year:'numeric'})}</time></div><h3>{post.title}</h3><p>{post.body.slice(0,140)}{post.body.length>140?'…':''}</p><button className="text-link" onClick={()=>setArticle(post)}>Read announcement <ArrowUpRight size={17}/></button></div></article>):<><a className="bulletin-feature" href="https://www.facebook.com/pupotsanNHS/photos/1500029802133880/" target="_blank" rel="noreferrer"><span className="pill">FROM OUR FACEBOOK PAGE</span><h3>Ready for<br/>Senior High?</h3><p>View the school’s enrollment post, then contact the school to confirm the current schedule.</p><span className="text-link">View enrollment post <ArrowUpRight size={18}/></span></a><div className="bulletin-side"><span className="eyebrow">KEEP IN TOUCH</span><h3>The latest from<br/>our school community.</h3><p>School advisories, activities, and community stories are shared on the Pupotsan National High School Facebook page.</p><a className="button button-outline" href={FACEBOOK} target="_blank" rel="noreferrer">Visit our Facebook page <ExternalLink size={16}/></a></div></>}</div></section>
      <section className="enrollment-section section" id="enrollment"><div className="container enrollment-grid"><div><p className="eyebrow">YOUR NEXT CHAPTER</p><h2>Let’s get you<br/><em>ready for school.</em></h2><p>{c.enrollment}</p><div className="enrollment-offering"><span className="offering-label">SENIOR HIGH SCHOOL OFFERING</span>{c.seniorHighStrands.map(strand=><strong key={strand}>{strand}</strong>)}<span>{c.seniorHighCertification}{c.acceptsAls?' · ALS learners accepted':''}</span></div><a className="button button-gold" href={FACEBOOK} target="_blank" rel="noreferrer">Ask about enrollment <ArrowUpRight size={18}/></a><p className="enrollment-note">Please confirm dates and requirements with the school before your visit.</p></div><div className="enrollment-steps"><div className="enroll-step"><span>01</span><div><h3>Connect with the school</h3><p>Ask about enrollment dates and the process for your grade level.</p></div></div><div className="enroll-step"><span>02</span><div><h3>Prepare your documents</h3><p className="preserve-lines">{c.requirements}</p></div></div><div className="enroll-step"><span>03</span><div><h3>Visit and complete enrollment</h3><p>Follow the school’s instructions and confirm your next steps with the enrollment staff.</p></div></div></div></div></section>
      <section className="section container campus-section" id="campus-life"><div className="section-heading"><div><p className="eyebrow">BEYOND THE CLASSROOM</p><h2>Life at Pupotsan</h2></div><p>Learning, friendships, and moments<br/>that bring our community together.</p></div>{c.gallery.length?<div className="gallery-grid">{c.gallery.map(p=><button className="gallery-item" key={p.id} onClick={()=>setPhoto(p)}><img src={p.url} alt={p.caption} loading="lazy"/><span>{p.caption}<ArrowUpRight size={18}/></span></button>)}</div>:<div className="campus-callout"><div><h3>A closer look at our school.</h3><p>See school activities and community photos on our Facebook page.</p></div><a className="button button-green" href={FACEBOOK} target="_blank" rel="noreferrer">Explore campus life <ArrowUpRight size={18}/></a></div>}</section>
      <section className="faq-section section container"><div><p className="eyebrow">A LITTLE GUIDANCE</p><h2>Questions?<br/>Start here.</h2></div><Accordion type="single" collapsible className="faq-list"><AccordionItem value="dates"><AccordionTrigger>When can I enroll?</AccordionTrigger><AccordionContent>{c.enrollment}</AccordionContent></AccordionItem><AccordionItem value="documents"><AccordionTrigger>What documents should I bring?</AccordionTrigger><AccordionContent>{c.requirements}</AccordionContent></AccordionItem><AccordionItem value="offerings"><AccordionTrigger>What Senior High programs are available?</AccordionTrigger><AccordionContent>Please contact the school for its current Senior High School offerings and guidance on choosing your program.</AccordionContent></AccordionItem><AccordionItem value="transfer"><AccordionTrigger>How can transfer students inquire?</AccordionTrigger><AccordionContent>Message the school’s Facebook page or visit the school. Let the staff know your grade level and that you are transferring so they can explain the next steps.</AccordionContent></AccordionItem></Accordion></section>
      <section className="contact-section" id="contact"><div className="container contact-inner"><div><p className="eyebrow">WE’RE HERE TO HELP</p><h2>Come say hello.</h2><p>Taod-oy, Magallanes, Agusan del Norte, Philippines</p></div><div className="contact-actions"><a className="button button-green" href={FACEBOOK} target="_blank" rel="noreferrer">Contact the school <ArrowUpRight size={18}/></a><a className="text-link" href="https://www.google.com/maps/search/?api=1&query=Pupotsan+National+High+School+Taod-oy+Magallanes+Agusan+del+Norte" target="_blank" rel="noreferrer"><MapPin size={18}/> Find us on Google Maps</a></div></div></section>
    </main>
    <footer><div className="container footer-top"><a href="#" className="brand footer-brand"><img src="/school-logo.png" alt="School seal" width="54" height="54"/><span>PUPOTSAN<span>NATIONAL HIGH SCHOOL</span></span></a><div className="footer-links"><a href="#about">About the school</a><a href="#enrollment">Enrollment</a><a href={FACEBOOK} target="_blank" rel="noreferrer">Facebook <ArrowUpRight size={14}/></a></div></div><div className="container footer-bottom"><span>Pupotsan National High School · Magallanes District</span><a href="/admin">Manage website <ArrowUpRight size={14}/></a></div></footer>
    <Dialog open={!!article} onOpenChange={open=>!open&&setArticle(null)}><DialogContent className="article-dialog"><DialogHeader><DialogTitle>{article?.title}</DialogTitle><DialogDescription>{article?.category} · {article?.date}</DialogDescription></DialogHeader>{article?.image&&<img src={article.image} alt={article.title}/>}<p className="preserve-lines">{article?.body}</p>{article?.source&&<a className="text-link" href={article.source} target="_blank" rel="noreferrer">Original Facebook post <ArrowUpRight size={16}/></a>}</DialogContent></Dialog>
    <Dialog open={!!photo} onOpenChange={open=>!open&&setPhoto(null)}><DialogContent className="photo-dialog"><DialogHeader><DialogTitle>{photo?.caption}</DialogTitle><DialogDescription>Pupotsan National High School</DialogDescription></DialogHeader>{photo&&<img src={photo.url} alt={photo.caption}/>}<a className="text-link" href={photo?.source||FACEBOOK} target="_blank" rel="noreferrer">View on Facebook <ArrowUpRight size={16}/></a></DialogContent></Dialog>
  </>;
}
