export const FACEBOOK = 'https://www.facebook.com/pupotsanNHS/';
export type NewsPost = {id:string; title:string; category:string; date:string; body:string; image:string; source:string};
export type SchoolContent = { notice:string; enrollment:string; requirements:string; seniorHighStrands:string[]; seniorHighCertification:string; acceptsAls:boolean; heroImage:string; heroSource:string; gallery:{id:string;url:string;caption:string;source:string}[]; posts:NewsPost[] };
export const DEFAULT_CONTENT:SchoolContent = {
  notice:'Enrollment questions? Connect with the school for the latest schedule and requirements.',
  enrollment:'For the current enrollment schedule, contact Pupotsan National High School through its Facebook page or visit the school in Taod-oy, Magallanes.',
  requirements:'Ask the school for the current checklist for your grade level. Requirements may differ for incoming, returning, ALS, and transfer students.',
  seniorHighStrands:['Electrical Installation and Maintenance (EIM)'],
  seniorHighCertification:'National Certificate II (NC II)',
  acceptsAls:true,
  heroImage:'/campus.jpg', heroSource:'https://www.facebook.com/photo/?fbid=1071456204991244&set=a.441133878023483', gallery:[{id:'opening-1',url:'/school-opening.jpg',caption:'Opening of classes · School Year 2026–2027',source:'https://www.facebook.com/photo/?fbid=1573619314774928&set=pcb.1573621404774719'},{id:'opening-2',url:'/school-community.jpg',caption:'A school community that welcomes every learner',source:'https://www.facebook.com/photo/?fbid=1573619431441583&set=pcb.1573621404774719'},{id:'opening-3',url:'/school-welcome.jpg',caption:'Together for a meaningful school year',source:'https://www.facebook.com/photo/?fbid=1573619894774870&set=pcb.1573621404774719'}], posts:[{id:'opening-classes-2026',title:'A blessed and meaningful opening of classes',category:'Campus life',date:'2026-06-08',body:'Today marks the beginning of another exciting academic journey as we warmly welcomed our learners for the First Day of School. Pupotsan National High School shared its welcome for School Year 2026–2027 and thanked its guests, partners, teachers, families, and learners for building a safe, inclusive, and learner-centered environment.',image:'/school-opening.jpg',source:'https://www.facebook.com/pupotsanNHS/posts/pfbid0tWJDR22Zr1TQgT3fDeJvpP3rZWwimvZsubQgq6sQyfR7oFdT6ZHpU94pawNbRU2ql'},{id:'suspension-advisory-2026',title:'Class suspension advisory',category:'Announcement',date:'2026-08-12',body:'Please check the official Facebook post for the complete class suspension advisory and return-to-class details. Confirm the latest school notice before making plans.',image:'/school-welcome.jpg',source:'https://www.facebook.com/pupotsanNHS/posts/pfbid02uCV8pNsU41FEE7REux3XUuMUR1nyRHyS55i1uu5B88Qbzv7LHet38QndYpGVtakJl'}]
};
